[colors]
background={{colors.surface.default.hex}}66
text={{colors.on_surface.default.hex}}ff
match={{colors.primary.default.hex}}ff
# Selection is 60% (99) to make it stand out against the 40% (66) background
selection={{colors.primary_container.default.hex}}99 
selection-text={{colors.on_primary_container.default.hex}}ff
selection-match={{colors.primary.default.hex}}ff
# Border is 60% (99) to be visible but not overwhelming
border={{colors.outline.default.hex}}99

[main]
font=JetBrains Mono:weight:bold:size=10
prompt="❯ "
padding-left=15
padding-right=15
width=40
line-height=25
border-width=2
fields=name,generic,comment,categories,filename
terminal=kitty
