general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = {{image}}   # Matugen automatically provides the current image path
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba({{colors.secondary.default.hex_stripped}}99)
  font_size = 32
  font_family = JetBrains Mono Bold
  position = 0, 300
  halign = center
  valign = center
}


# TIME
label {
    monitor =
    text = $TIME12
    color = rgba({{colors.primary.default.hex_stripped}}99)
    font_size = 120
    font_family = JetBrains Mono Bold
    position = 0, -300
    halign = center
    valign = top
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba({{colors.primary.default.hex_stripped}}66)
    inner_color = rgba({{colors.surface.default.hex_stripped}}66)
    font_color = rgba({{colors.on_surface.default.hex_stripped}}66)
    fade_on_empty = false
    placeholder_text = パスワード入力...
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}
