general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = screenshot
    color = rgba(20, 20, 20, 1.0)
    blur_passes = 3 
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(153, 153, 153, 1.0)
  font_size = 32
  font_family = UbuntuMono Nerd Font
  position = 0, 200
  halign = center
  valign = center
}

# TIME
label {
    monitor =
    text = $TIME12
    color = rgba(255, 255, 255, 1.0)
    font_size = 64
    font_family = UbuntuMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    # Matching your Waybar transparency (0.7 alpha)
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(20, 20, 20, 0.2)
    font_color = rgb(255, 255, 255)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    # Match the border-radius from your hardware groups and tooltips
    rounding = 8
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    position = 0, -20
    halign = center
    valign = center
}

# USER ICON (Optional, using text for a minimal look)
label {
    monitor =
    text =   $USER
    color = rgba(255, 255, 255, 0.8)
    font_size = 14
    font_family = Inter
    position = 0, -80
    halign = center
    valign = center
}
