# BEGIN_KITTY_FONTS
font_family      family="Cascadia Code NF"
bold_font        CascadiaCodeNFRoman-Bold
italic_font      CascadiaCodeNF-Italic
bold_italic_font CascadiaCodeNF-BoldItalic
font_size        14.0
font_features    CascadiaCodeNFRoman-Regular +calt +ss01 +ss02 +ss03 +ss19 +ss20
font_features    CascadiaCodeNFRoman-Bold +calt +ss01 +ss02 +ss03 +ss19 +ss20
font_features    CascadiaCodeNF-Italic +calt +ss01 +ss02 +ss03 +ss19 +ss20
font_features    CascadiaCodeNF-BoldItalic +calt +ss01 +ss02 +ss03 +ss19 +ss20

# --- Window Style ---
window_padding_width 20
#background_opacity 0.90
# Hide the title bar to let Niri handle the "roundy" look
hide_window_decorations yes

enable_audio_bell no

include colors.conf
